services:
  - type: web
    name: llm-quiz-solver
    env: docker
    healthCheckPath: /ping
    plan: free
    envVars:
      - key: SECRET_STRING
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AIPIPE_API_KEY
        sync: false
